---
title: Linear Algebra
author: Brendan Knapp
date: '2018-12-02'
slug: index
categories:
  - data-science-notes
tags:
  - data-science-from-scratch
  - statistics
  - programming
  - r
  - python
  - rcpp
image:
  caption: ''
  focal_point: 'Smart'
summary: 'Common linear algebra operations.'
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
citation_url: https://knapply.com/post/linear-algebra/
editor_options: 
  chunk_output_type: console
---

> _This post was last updated on `r format(Sys.Date(), "%Y-%m-%d")`._

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, comment = "#>", message = FALSE, warning = FALSE)

options(width=90)

source(here::here("static/R/html-helpers.R"))
source(here::here("static/R/citation.R"))
source(here::here("static/R/wrangle_plot_save.R"))
```



# Setup

## R

### Base R



```{r}
r_mat <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9),
                nrow = 3, ncol = 3)

r_mat
```

## Python

### NumPy

```{python}
import numpy as np

np_mat = np.array([[1, 4, 7],
                   [2, 5, 8],
                   [3, 6, 9]])

np_mat
```



# Scalar Multiplication

$$
  2 
\cdot
\begin{pmatrix}
  1   &  4   &  7  \\
  2   &  5   &  8  \\
  3   &  6   &  9  \\
\end{pmatrix}
  =
\begin{pmatrix}
  1 \cdot 2  &  4 \cdot 2  &  7 \cdot 2 \\
  2 \cdot 2  &  5 \cdot 2  &  8 \cdot 2 \\
  3 \cdot 2  &  6 \cdot 2  &  9 \cdot 2 \\
\end{pmatrix}
  =
\begin{pmatrix}
  2   &  8   &  14  \\
  4   &  10   &  16  \\
  6   &  12   &  18  \\
\end{pmatrix}
$$

```{r, eval = FALSE, echo=FALSE}
as_latex_matrix <- function(x, append = "") {
  stopifnot(is.matrix(x))
  apply(x, 1, function(y) {
    cat(paste0(y, glue::glue(" {append}"), collapse = "  &  "), 
              "\\\\\n")
  })
  invisible(NULL)
}
as_latex_matrix(2 * r_mat)

as_latex_matrix(r_mat, "\\cdot 2")
```


## R

### Base R

```{r}
r_mat * 2
```

## Rcpp

### Built-in

```{Rcpp}
// [[Rcpp::plugins(cpp17)]]
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
auto cpp_scalar_multiply(NumericMatrix x, int scalar) {
  auto out = x * scalar; 

  return out;
}
```

```{r}
cpp_scalar_multiply(r_mat, 2)
```

### RcppArmadillo

```{Rcpp}
// [[Rcpp::plugins(cpp17)]]
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
using namespace Rcpp;

// [[Rcpp::export]]
auto cpp_arma_scalar_multiply(NumericMatrix x, int scalar) {
  auto arma_matrix = as<arma::mat>(x);
  auto out = arma_matrix * scalar;
  
  return wrap(out);
}
```

```{r}
cpp_arma_scalar_multiply(r_mat, 2)
```



## Python

### NumPy

```{python}
res = np_mat * 2
print(res)
```


# Matrix-Vector Multiplication

$$
\begin{pmatrix}
  1   &  4   &  7  \\
  2   &  5   &  8  \\
  3   &  6   &  9  \\
\end{pmatrix}
\cdot
\begin{pmatrix}
  1 \\
  2 \\
  3 \\
\end{pmatrix} 
  \\=
\begin{pmatrix}
  1 \cdot 1 + 4 \cdot 2 + 7 \cdot 3 \\
  2 \cdot 1 + 5 \cdot 2 + 8 \cdot 3 \\
  3 \cdot 1 + 6 \cdot 2 + 9 \cdot 3 \\
\end{pmatrix}
  \\=
\begin{pmatrix}
  1 + 8 + 21 \\
  2 + 10 + 24 \\
  3 + 12 + 27 \\
\end{pmatrix}
  \\=
\begin{pmatrix}
  30  \\
  36  \\
  42  \\
\end{pmatrix}
$$

## R

### Base R

```{r}
r_mat %*% c(1,
            2,
            3)
```

## Rcpp

### Built-in

### RcppArmadillo

## Python

### NumPy

```{python}
res = np_mat.dot(np.array([[1],
                           [2],
                           [3]]))
print(res)
```

# Vector-Matrix Multiplication


$$
\begin{pmatrix}
  1 & 2 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
  1   &  4   &  7  \\
  2   &  5   &  8  \\
  3   &  6   &  9  \\
\end{pmatrix}
  \\=
\begin{pmatrix}
  1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3 ~&~ 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 ~&~ 1 \cdot 7 + 2 \cdot 8 + 3 \cdot 9
\end{pmatrix}
  \\=
\begin{pmatrix}
  1 + 4 + 9 ~&~ 4 + 10 + 18 ~&~ 7 + 16 + 27
\end{pmatrix}
  \\=
\begin{pmatrix}
14   &  32   &  50  \\
\end{pmatrix}
$$

### R

#### Base R

```{r}
c(1, 2, 3) %*% r_mat
```

### Rcpp

#### Built-in

#### RcppArmadillo

### Python

#### NumPy

```{python}
res = np.array([[1, 2, 3]]).dot(np_mat)
print(res)
```



</p>
</details>

```{r child=here::here("static/R/environment-details.Rmd")}
```


