---
title: Mean
author: Brendan Knapp
date: '2018-11-12'
slug: index
categories:
  - data-science-notes
tags:
  - data-science-notes
  - statistics
  - central-tendency
  - r
  - python
  - rcpp
image:
  caption: ''
  focal_point: 'Smart'
summary: 'Calculating the arithmetic mean of a sequence.'
output:
  blogdown::html_page:
    toc: true
    toc_depth: 5
citation_url: https://knapply.com/post/mean/
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, comment = "#>", warning = FALSE, message = FALSE)

options(width=90)

source(here::here("static/R/html-helpers.R"))
source(here::here("static/R/citation.R"))
source(here::here("static/R/wrangle_plot_save.R"))
```


# R

## Base R

```{r}
r_vector <- c(126, 793, 999, 525, 851, 798, 120, 714, 852, 151,
              190, 41, 612, 826, 507, 105, 14, 237, 669, 7)

mean(r_vector)
```

# Rcpp

## Sugar

```{Rcpp}
#include <Rcpp.h>

// [[Rcpp::export]]
double rcpp_sugar_mean(Rcpp::NumericVector x) {
  return Rcpp::mean(x);
}
```


```{r}
r_vector <- c(126, 793, 999, 525, 851, 798, 120, 714, 852, 151,
              190, 41, 612, 826, 507, 105, 14, 237, 669, 7)

rcpp_sugar_mean(r_vector)
```

## Custom

### Blueprint

```{Rcpp}
//[[Rcpp::plugins(cpp17)]]
#include <Rcpp.h>

// [[Rcpp::export]]
double cpp_mean_blueprint(const Rcpp::NumericVector& x) {
  double n = std::size(x);
  return std::accumulate(std::begin(x), std::end(x), 0.0) / n;
}
```

```{r}
cpp_mean_blueprint(r_vector)
```

### Templated

```{Rcpp}
//[[Rcpp::plugins(cpp17)]]
#include <Rcpp.h>

template <int RTYPE>
auto cpp_mean_(const Rcpp::Vector<RTYPE>& x) {
  const auto out = std::accumulate(std::begin(x), std::end(x), 0.0) / std::size(x);
  
  return Rcpp::wrap(out);
}

// [[Rcpp::export]]
SEXP cpp_mean(const SEXP& x) {
  switch( TYPEOF(x) ) {
    case INTSXP:
      return cpp_mean_<INTSXP>(x);
    case REALSXP:
      return cpp_mean_<REALSXP>(x);
  }
  Rcpp::warning("Invalid SEXPTYPE %d (%s).\n", TYPEOF(x), Rcpp::type2name(x));
  return R_NilValue;
}
```

```{r}
cpp_mean(r_vector)
```

### RcppParallel

_Note:_ `struct Sum` comes from the ["Rcpp Gallery"](http://gallery.rcpp.org/articles/parallel-vector-sum/).


```{Rcpp}
//[[Rcpp::plugins(cpp14)]]
#include <Rcpp.h>
// [[Rcpp::depends(RcppParallel)]]
#include <RcppParallel.h>

struct Sum : public RcppParallel::Worker {
   const RcppParallel::RVector<double> input;
   double value;
   
   Sum(const Rcpp::NumericVector input) : input(input), value(0) {}
   Sum(const Sum& sum, RcppParallel::Split) : input(sum.input), value(0) {}
   
   void operator()(std::size_t begin, std::size_t end) {
      value += std::accumulate(input.begin() + begin, input.begin() + end, 0.0);
   }
   void join(const Sum& rhs) { 
      value += rhs.value; 
   }
};

// [[Rcpp::export]]
double cpp_par_mean(Rcpp::NumericVector x) {
   Sum sum(x);
   parallelReduce(0, x.length(), sum);

   return sum.value / x.size();
}
```

```{r}
cpp_par_mean(r_vector)
```



# Python

## Pure Python

```{python}
import statistics

py_list = [126, 793, 999, 525, 851, 798, 120, 714, 852, 151,
           190, 41, 612, 826, 507, 105, 14, 237, 669, 7]

res = statistics.mean(py_list)
print(res)
```

## NumPy

```{python}
import numpy as np

numpy_array = np.array(py_list)

res = np.mean(numpy_array)
print(res)
```

## Numba

```{python}
import numba

@numba.jit()
def numba_mean(x):
  return np.mean(x)

res = numba_mean(numpy_array)
print(res)
```

### Parallel

```{python}
@numba.jit(parallel = True)
def numba_par_mean(x):
  return np.mean(x)

res = numba_par_mean(numpy_array)
print(res)
```

## CuPy

```{python}
import cupy as cp

cupy_array = cp.array(numpy_array, copy = True)

res = cp.mean(cupy_array)
print(res)
```


# Shootout

<details>
<summary> Test Setup </summary>
<p>


```{r, message=FALSE, warning=FALSE}
library(reticulate)
library(tidyverse)
library(bench)
```

Create R Data

```{r}
set.seed(831)
r_data <- seq(-1e4, 1e4, by = 0.2) %>%
  sample(replace = TRUE, size = 1e7) %>%
  sample()

validation_data <- r_data
```

Transfer to Python

```{python}
from copy import deepcopy

numpy_data = np.array(deepcopy(r.r_data))
cupy_data = cp.array(numpy_data, copy = True)
```


Do all the data match?

```{r}
are_equal <- list(r_data, py$numpy_data,
                  py$cp$asnumpy(py$cupy_data)) %>% 
    map_lgl(~ all.equal(validation_data, as.vector(.x)))

stopifnot(
  all(are_equal)
)
```

```{r}
(n <- scales::comma(length(r_data)))
(mem <- capture.output(pryr::object_size(r_data)))
```

</p>
</details>


<details>
<summary> `bench::mark()` </summary>
<p>

```{r, include=FALSE}
gc()
```


```{r}
res <- mark(
  mean(r_data),
  rcpp_sugar_mean(r_data),
  cpp_mean(r_data),
  cpp_par_mean(r_data),
  py_run_string("np.mean(numpy_data)", convert = FALSE),
  py_run_string("numba_mean(numpy_data)", convert = FALSE),
  py_run_string("numba_par_mean(numpy_data)", convert = FALSE),
  py_run_string("cp.mean(cupy_data)", convert = FALSE),
  min_iterations = 5,
  check = FALSE, filter_gc = FALSE
)
```

</p>
</details>


```{r, echo=FALSE}
as_chunk(here::here("static/R/wrangle_plot_save.R"))
```

<details>
<summary> `wrangle_plot_save()` </summary>
<p>

```{r wrangle_plot_save, eval=FALSE}
```

</p>
</details>

<details>
<summary> `write_gg()` </summary>
<p>

```{r write_gg, eval=FALSE}
```

</p>
</details>


<details>
<summary> `res_gg` </summary>
<p>

```{r, fig.align='center', fig.width=9, fig.height=11, message=FALSE, warning=FALSE}
res_gg <- wrangle_plot_save(res, .n = n, .mem = mem, 
                            .title = "Benchmarks: Arithmetic Mean")
```



```{r, eval=FALSE}
res_gg
```

</p>
</details>


```{r, echo=FALSE, fig.align='center', fig.width=9, fig.height=10, message=FALSE, warning=FALSE}
res_gg
```


<details>
<summary> Post Test Checks </summary>
<p>

Do all methods obtain the same results?

```{r}
(control_res <- mean(r_data))

c(
  rcpp_sugar_mean(r_data),
  cpp_mean(r_data),
  cpp_par_mean(r_data),
  py$np$mean(py$numpy_data),
  py$numba_mean(py$numpy_data),
  py$numba_par_mean(py$numpy_data),
  py$cp$asnumpy(py$cp$mean(py$cupy_data))
  )

are_equal <- c(
  
  rcpp_sugar_mean(r_data),
  cpp_mean(r_data),
  cpp_par_mean(r_data),
  py$np$mean(py$numpy_data),
  py$numba_mean(py$numpy_data),
  py$numba_par_mean(py$numpy_data),
  py$cp$asnumpy(py$cp$mean(py$cupy_data))
  
  ) %>% 
  map_lgl(all.equal, control_res)

stopifnot(
  all(are_equal)
)
```


Did the input data remain unchanged?

```{r}
are_equal <- list(r_data, 
                  py$numpy_data,
                  py$cp$asnumpy(py$cupy_data)) %>% 
    map_lgl(~ all.equal(validation_data, as.vector(.x)))

stopifnot(
  all(are_equal)
)
```

</p>
</details>

```{r child=here::here("static/R/environment-details.Rmd")}
```

