---
title: Functions
author: Brendan Knapp
date: '2018-11-01'
slug: index
categories:
  - tutorial
  - data-science-from-scratch
  - programming
tags:
  - R
  - Python
  - Cpp
  - tutorial
  - data-science-from-scratch
  - programming
image:
  caption: ''
  focal_point: 'Smart'
summary: Defining functions in R, Python, and C++/Rcpp.
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
citation_url: https://knapply.com/post/functions/
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(cache = TRUE)
```



```{Rcpp, ref.label=knitr::all_rcpp_labels(), include=FALSE}
```

## Define `doubler_*()` Function

<table style="font-size:14px" class="table table-bordered">
<tr>
<td valign="top">
      
```{r}
r_doubler <- function(x) {
  x * 2
}
```
      
</td>
<td valign="top">
    
```{python}
def py_doubler(x):
  return x * 2
```
    
</td>
</td>
<td valign="top">

```{Rcpp}
#include <Rcpp.h>

// [[Rcpp::export]]
int cpp_doubler(int x) {
  return x * 2;
}
```
  
</td>
</tr>
</table>


## Run `doubler_*()` Function

<table style="font-size:14px" class="table table-bordered">
<tr>
<td valign="top">
      
```{r}
r_doubler(x = 4)
```
      
</td>
<td valign="top">
    
```{python}
print(py_doubler(x = 4))
```
    
</td>
</td>
<td valign="top">

```{r}
cpp_doubler(x = 4)
```
  
</td>
</tr>
</table>


<br><br><br>

### Citation

```{r, echo=FALSE}
title <- rmarkdown::metadata$title
index <- stringr::str_to_lower(stringr::str_replace_all(title, "\\s+", "-"))
author <- rmarkdown::metadata$author
date <- as.Date(rmarkdown::metadata$date)
year <- lubridate::year(date)
month <- months.Date(date, abbreviate = TRUE)
day <- lubridate::day(date)
citation_url <- rmarkdown::metadata$citation_url
```

For attribution, you can cite this page as

```{r, echo=FALSE, comment=NA, results='markup', class.output='citation'}
glue::glue('Knapp, B. (<<year>>, <<month>>. <<day>>). <<title>>. Retrieved from <<citation_url>>',
           .open = "<<", .close = ">>")
```


BibTex


```{r, echo=FALSE, comment=NA, results='markup', class.output='citation'}
build_bibtex <- function() {
  # cat("```\n")
  out <- glue::glue('@misc{<<index>>,
                      author = {Knapp, Brendan},
                      title  = {<<title>>}
                      url    = {<<citation_url>>},
                      year   = <<year>>
                      month  = <<month>>
                      day    = <<day>>
                    }',
             .open = "<<", .close = ">>")
  cat(out)
  # cat("\n```\n")
}

build_bibtex()
```
