---
title: Standard Deviation
author: Brendan Knapp
date: '2018-11-09'
slug: index
categories:
  - programming
  - tutorial
tags:
  - programming
  - r
  - python
  - cpp
  - rcpp
  - numpy
image:
  caption: ''
  focal_point: 'Smart'
summary: 'Calculating standard deviation'
output:
  blogdown::html_page:
    toc: true
    toc_depth: 3
citation_url: https://knapply.com/post/foundational-programming/
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, comment = "#>")

source(here::here("static/R/html-helpers.R"))
source(here::here("static/R/citation.R"))
```

## Purpose

Quantify amount of variation/spread/dispersion of values.

## Equations

$\sigma_x = \sqrt{ \frac{\sum(x - \mu_x)^2} {N-1} }$

$\sigma_x = sqrt({ \frac{sum(~(x - mean(x)~)^2} {(N-1)}})$

$numerator = sum(~(x-mean(x)~)^2$

$mean = \frac {sum(x)} {length(x)}$

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">




# By Hand

```{r, echo=FALSE, cache=FALSE}
as_chunk("standard-deviation/r-sd1.R")
as_chunk("standard-deviation/rcpp-sd1.cpp")
as_chunk("combo/helpers.h")
as_chunk("combo/cpp-sd1.cpp")
as_chunk("standard-deviation/numpy-sd1.py")
```

```{r, echo=FALSE}
start_tabset()
add_menu_tab("r-sd1", is_active = TRUE)
add_menu_tab("rcpp-sd1", is_active = FALSE)
add_menu_tab("cpp-sd1", is_active = FALSE)
add_menu_tab("numpy-sd1", is_active = FALSE)
end_menu()
```


```{r, echo=FALSE}
start_tab_content()
add_active_tab("r-sd1")
embed_github_link("standard-deviation/r-sd1.R")
```

```{r r-sd1}
```


```{r, echo=FALSE}
end_tab()
add_other_tab("rcpp-sd1")
embed_github_link("standard-deviation/rcpp-sd1.cpp")
```

```{Rcpp rcpp-sd1, class.source="cpp-cpp"}
```

```{r}
cpp_standard_deviation(1:20)
```


```{r, echo=FALSE}
end_tab()
add_other_tab("cpp-sd1")
embed_github_link("standard-deviation/cpp-sd1.cpp")
```

```{Rcpp cpp-sd1-header, eval=FALSE, class.source="cpp-header"}
```

```{Rcpp cpp-sd1, eval=FALSE, class.source="cpp-cpp"}
```

```{bash, eval=FALSE}
g++ -std=c++17 cpp-sd1.cpp -o cpp-sd1.cpp && ./cpp-sd1
```

```{bash, echo=FALSE}
cd /mnt/c/Users/Windows/Documents/tutorial-gists/sections/combo/ &&
  g++ -std=c++17 cpp-sd1.cpp -o cpp-sd1 &&
  ./cpp-sd1
```


```{r, echo=FALSE}
end_tab()
add_other_tab("numpy-sd1")
embed_github_link("standard-deviation/numpy-sd1.py")
```

```{python numpy-sd1}
```

```{r, echo=FALSE}
end_tab()
end_tabset()
```




